### ISSUE TITLE
Unhandled Exception when receiving text from non-iPhone

### ISSUE THREAD

**Issue by SSStevexe** [Skittyblock/Pokebox#1]
[ Produced on iOS 13.3 | iPhone 11 Pro Max ] 
As title writes, tweak will crash on receipt of non-iPhone text message when phone is in unlocked state. Evidence is clear when phone did not crash receiving a non-iPhone text message and the preview string was Unicode. 

Was unable to capture screen shot.

Possibility on handling iPhone texts vs Non-iPhone must be different.

No issues when phone is locked, only when animation banner appears when phone is unlocked.

Steps to reproduce:

1. Have tweak installed
2. Make sure phone is unlocked state
3. Use a free non-iPhone text messaging website. I used: http://www.textem.net/index.php
4. Send text to unlocked iPhone and wait for notification banner to appear.
5. You will see the banner with the persons name in the title, instantly will be thrown into springboard safe mode.

EDIT:

Found the exact issue.

When going into:
 iOS settings -> Notifications -> Show Previews 
If this setting is set to "Never," then, it seems that there is an access violation when attempting to display text preview via PokeBox.

Solution:
Set the option to "When Unlocked" and everything functions fantastically.

**Comment by Skittyblock** [comment]
Thank you very much for the detailed report and steps to reproduce the crash! I just fixed this in the latest commit, and I'll have it included the next Pokébox update (soon), so I'm closing this.
